<?php

function signin_message_menu(){
    $items = array();
    $items['greeting'] = array(
        'title' => 'Hello Friend',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function signin_message_user_login(&$edit, $account) {
    $_GET['destination'] = 'greeting';
}

function say_hello() {
    return '<p>Hello my dear player</p>';
}
